from datetime import datetime

from uuid import UUID, uuid4

from sqlalchemy import String, Boolean, DateTime, ForeignKey, func
from sqlalchemy.orm import Mapped, mapped_column, relationship

from .db.base import Base

class User(Base):
    __tablename__ = 'users'

    # Mapped is just for type hinting for Python; mapped_column is the actual physical rule.

    id: Mapped[UUID] = mapped_column(
        primary_key=True, # For 'default', the value is generated by Python.
        default=uuid4
    )

    email: Mapped[str] = mapped_column(
        String(100),
        unique=True,
        index=True,
        nullable=False
    )

    password_hash: Mapped[str] = mapped_column(
        String(255),
        nullable=False
    )

    is_active: Mapped[bool] = mapped_column(
        Boolean,
        default=True,
        nullable=False
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(), # For 'server_default', the value is generated by PostgreSQL (the database).

        # 'func' represents the collection of built-in SQL functions, like COUNT (func.count), LOWER (func.lower), SUM (func.sum), and NOW (func.now).

        nullable=False
    )

    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False
    )

    # RELATIONSHIPS:
    """ The import is wrapped in string literals in type hinting, is a valid syntax.
    Python simply skips it, but SQLAlchemy, since we are inheriting every model from the DeclarativeBase class,
    already having a registry dict having each models' name and their respective class object as the value,
    imports everything correctly. ie; for Python it is just valid and skippable, but SQLAlchemy, combined, does the forward import work. """

    oauth_tokens: Mapped[list['UserOAuthToken']] = relationship( # 'list' is because it's a one-to-many relationship; the user could have many repos.
        back_populates='user', # Because the corresponding attribute on the other side is named 'user'.
        cascade='all, delete-orphan' # This is two rules, actually: 'all', a shorthand for rules like save-update, merge, refresh-expire, expunge, delete, and 'delete-orphan'.

    )

    """ 'cascade' defines what automatically happens to the child if something has happened to the parent;
    'cascade=...' is the ORM-level config. """

class UserOAuthToken(Base):
    __tablename__ = 'user_oauth_tokens'

    id: Mapped[UUID] = mapped_column(
        primary_key=True,
        default=uuid4
    )

    user_id: Mapped[UUID] = mapped_column(
        ForeignKey('users.id', ondelete='CASCADE'), # 'ondelete='CASCADE'' is the direct PostgreSQL-level of the cascade rule in relationship for both ORM-level and database-level integrity.
        nullable=False
    )

    provider: Mapped[str] = mapped_column(
        String(100),
        nullable=False
    )

    access_token: Mapped[str] = mapped_column(
        String(500),
        nullable=False
    )

    refresh_token: Mapped[str | None] = mapped_column(
        String(500),
        nullable=True
    )

    expires_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False
    )

    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False
    )

    # RELATIONSHIPS:
    user: Mapped['User'] = relationship(
        back_populates='oauth_tokens'
    )
