"""add_unique_constraint_to_oauth_tokens

Revision ID: 52cb9da4cbfe
Revises: 627acfa587e0
Create Date: 2026-09-17 21:34:33.473466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52cb9da4cbfe'
down_revision: Union[str, Sequence[str], None] = '627acfa587e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_oauth_provider', 'user_oauth_tokens', ['user_id', 'provider'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_oauth_provider', 'user_oauth_tokens', type_='unique')
    # ### end Alembic commands ###
