from pydantic import BaseModel, Field

class MigrationPlanRequest(BaseModel):
    file_path: str
    line_number: int
    algorithm: str
    category: str
    code_content: str # Full file content
    target_standard: str | None = None  # eg. ML-DSA-65 (FIPS 204)

class MigrationPlanResponse(BaseModel):
    migrated_file_content: str = Field(description='The complete, updated file content with modern imports and quantum-safe code')
    explanation: str = Field(default='Migrated to post-quantum cryptography.', description='Clear explanation of the changes made and any new imports required')
    library_required: str = Field(default='oqs-python', description="Python package or dependency required, e.g. 'oqs-python' or 'cryptography'")
    complexity: str = Field(default='LOW', description='Migration complexity: LOW, MEDIUM, or HIGH')

class MigrationExecuteRequest(BaseModel):
    repo_full_name: str = Field(description="GitHub repository full name, e.g. 'octocat/hello-world'")
    github_token: str = Field(description="User's GitHub OAuth token with repo write permissions")
    file_rel_path: str = Field(description="Relative path of file in repo, e.g. 'src/auth/jwt.py'")
    migrated_file_content: str = Field(description='The updated code content generated by the planner')
    branch_name: str | None = Field(default=None, description='Optional custom branch name')

class MigrationExecuteResponse(BaseModel):
    success: bool
    branch: str | None = None
    repo: str | None = None
    diff: str | None = None
    error: str | None = None
    message: str
